# Support DM Hero development
# These are supported funding model platforms

github: # Flo0806  # Uncomment when GitHub Sponsors is enabled
buy_me_a_coffee: flo0806
# ko_fi: # Your Ko-fi username
# patreon: # Your Patreon username
# custom: ['https://your-custom-link.com']
