// Server-side entity icon utilities
// Duplicated from frontend composable for server use

const ITEM_TYPE_ICONS: Record<string, string> = {
  weapon: 'mdi-sword',
  armor: 'mdi-shield',
  ammunition: 'mdi-arrow-projectile-multiple',
  potion: 'mdi-bottle-tonic',
  scroll: 'mdi-script-text',
  artifact: 'mdi-star-circle',
  magical: 'mdi-auto-fix',
  quest_item: 'mdi-exclamation-thick',
  key: 'mdi-key-variant',
  map: 'mdi-map',
  consumable: 'mdi-fire',
  food: 'mdi-food-drumstick',
  drink: 'mdi-glass-mug-variant',
  poison: 'mdi-skull-crossbones',
  tool: 'mdi-hammer-wrench',
  lantern: 'mdi-flashlight',
  rope: 'mdi-hook',
  container: 'mdi-package-variant',
  bag: 'mdi-bag-personal',
  treasure: 'mdi-treasure-chest',
  gem: 'mdi-diamond-stone',
  jewelry: 'mdi-ring',
  currency: 'mdi-currency-usd',
  clothing: 'mdi-tshirt-crew',
  mundane: 'mdi-package-variant-closed',
  component: 'mdi-beaker',
  material: 'mdi-cube-outline',
  mount: 'mdi-horse',
  vehicle: 'mdi-carriage-passenger-door',
  figurine: 'mdi-chess-knight',
  idol: 'mdi-account-box',
  totem: 'mdi-totem-pole',
  relic: 'mdi-cross',
  banner: 'mdi-flag',
  orb: 'mdi-circle',
  horn: 'mdi-bugle',
  mirror: 'mdi-mirror-rectangle',
  crystal: 'mdi-rhombus-medium',
  trap: 'mdi-alert-circle',
}

const LOCATION_TYPE_ICONS: Record<string, string> = {
  city: 'mdi-city',
  town: 'mdi-home-city',
  village: 'mdi-home-group',
  castle: 'mdi-castle',
  fortress: 'mdi-shield-home',
  tower: 'mdi-tower-fire',
  dungeon: 'mdi-gate',
  cave: 'mdi-tunnel',
  mine: 'mdi-pickaxe',
  crypt: 'mdi-coffin',
  forest: 'mdi-pine-tree',
  mountain: 'mdi-image-filter-hdr',
  river: 'mdi-waves',
  lake: 'mdi-water',
  swamp: 'mdi-sprout',
  desert: 'mdi-weather-sunny',
  island: 'mdi-island',
  valley: 'mdi-terrain',
  coast: 'mdi-beach',
  oasis: 'mdi-palm-tree',
  glacier: 'mdi-snowflake',
  volcano: 'mdi-fire',
  canyon: 'mdi-image-filter-hdr',
  plains: 'mdi-grass',
  jungle: 'mdi-tree',
  waterfall: 'mdi-waterfall',
  temple: 'mdi-temple-buddhist',
  shrine: 'mdi-candelabra-fire',
  monastery: 'mdi-church',
  ruins: 'mdi-pillar',
  monument: 'mdi-pillar',
  graveyard: 'mdi-grave-stone',
  battlefield: 'mdi-sword-cross',
  arena: 'mdi-stadium',
  tavern: 'mdi-glass-mug-variant',
  shop: 'mdi-store',
  guild: 'mdi-account-group',
  bridge: 'mdi-bridge',
  road: 'mdi-road-variant',
  lighthouse: 'mdi-lighthouse',
  windmill: 'mdi-wind-turbine',
  quarry: 'mdi-shovel',
  farm: 'mdi-barn',
  manor: 'mdi-home-variant',
  palace: 'mdi-domain',
  camp: 'mdi-tent',
  portal: 'mdi-creation',
}

export function getItemTypeIcon(type: string | null | undefined, fallback = 'mdi-sword'): string {
  if (!type) return fallback
  return ITEM_TYPE_ICONS[type.toLowerCase()] || fallback
}

export function getLocationTypeIcon(type: string | null | undefined, fallback = 'mdi-map-marker'): string {
  if (!type) return fallback
  return LOCATION_TYPE_ICONS[type.toLowerCase()] || fallback
}
